#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

decomposePar

foamJob -parallel -screen potentialFoam

foamJob -parallel -screen simpleFoam

reconstructPar 

#------------------------------------------------------------------------------
